name: Swift CI/CD Build

on:
  #commit:
  push:
    branches:
      - master
    #pull-request:
  
jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

 #   - name: Navigate and list available schemes and SDKs
 #     run: |
 #       cd tesla
    #    xcodebuild -list 
       # xcodebuild -showsdks
     #   ls -la **/**

   # - name: Install CocoaPods dependencies
  #    run: |
   #     cd tesla
    #    pod install

    - name: Archive the Xcode project
      run: |
        cd tesla
        xcodebuild archive -workspace tesla.xcworkspace -configuration Debug -scheme tesla -destination generic/platform=iOS DEBUG_INFORMATION_FORMAT=dwarf-with-dsym -archivePath tesla.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ENABLE_BITCODE=NO > ~/build_log.txt
        cp ./build_log.txt ~/ 
        
    # ls && pwd

    - name: Generate IR for Veracode and create ZIP
      run: |
        cd ../
        brew tap veracode/tap
        brew install gen-ir
        gen-ir ~/build_log.txt ~/tesla.xcarchive --project-path tesla.xcodeproj --debug true 
        ls -la tesla.xcarchive
        zip -r tesla.zip tesla.xcarchive
        mv tesla.zip ../tesla.zip

        ls && pwd
